-- Insert Govee guides (English only for now)
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES
('govee-de-1', 'govee', 'de', 1,                                                                                     'Govee-App öffnen','Öffnet Sie die Govee-App auf Ihrem iOS- oder Android-Smartphone.','{}'),
('govee-de-2', 'govee', 'de', 2,                                                                                     'API-Schlüssel abrufen','Gehen Sie zu Profil > Einstellungen > API-Schlüssel. Kopieren Sie den vollständigen Schlüssel (er sieht aus wie eine UUID). Dies authentifiziert Ihre Geräte.','{„api_key“: „Ihr Govee-API-Schlüssel aus den App-Einstellungen. Wird zur Authentifizierung aller API-Anfragen verwendet.“}'),
('govee-de-3', 'govee', 'de', 3,                                                                                     'Gerät hinzufügen','Fügen Sie in der Govee-App Ihre Geräte hinzu und notieren Sie sich deren Namen. Sie müssen wissen, welches Gerät Sie steuern möchten', '{}'),
('govee-de-4', 'govee', 'de', 4,                                                                                     'Zugangsdaten eingeben','Fügen Sie Ihren API-Schlüssel ein. Geben Sie dann die MAC-Adresse des Geräts ein (zu finden unter den Geräteinformationen in der App, Format: XX:XX:XX:XX:XX:XX).','{„api_key“: „Ihr Govee-API-Schlüssel aus den App-Einstellungen. Wird zur Authentifizierung aller API-Anfragen verwendet.“, „device_id“: „Die MAC-Adresse Ihres Govee-Geräts. Zu finden auf der Geräteinfoseite der Govee-App. Format: XX:XX:XX:XX:XX:XX“}'),
('govee-de-5', 'govee', 'de', 5,                                                                                     'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um vor dem Speichern zu überprüfen, ob alles funktioniert.','{}');
                                                                                                                     
-- Insert Philips Hue guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('philips-hue-de-1', 'hue', 'de', 1,                                                                                 'Bridge lokalisieren','Sie benötigen eine Hue Bridge (physischer Hub), die mit Ihrem Netzwerk verbunden ist. Falls Sie keine haben, müssen Sie sich eine besorgen.','{}'),
('philips-hue-de-2', 'hue', 'de', 2,                                                                                 'Bridge-IP-Adresse','Ermitteln Sie die IP-Adresse Ihrer Bridge über Ihren Router. Suchen Sie nach einem Gerät namens „Philips Hue Bridge“ oder verwenden Sie die offizielle Hue-App, um sie zu finden.','{„bridge_ip“: „IP-Adresse Ihrer Hue Bridge in Ihrem Netzwerk. Beispiel: 192.168.1.50“}'),
('philips-hue-de-3', 'hue', 'de', 3,                                                                                 'Token generieren','Rufen Sie die Bridge unter http://[BRIDGE_IP]/debug/clip.html auf. Drücken Sie die Taste an der Bridge und erstellen Sie dann einen Benutzer. Kopieren Sie den zurückgegebenen Benutzernamen (dies ist Ihr API-Schlüssel).','{„api_key“: „Von der Bridge generierter API-Schlüssel (Benutzername). Diesen finden Sie in den Bridge-Einstellungen.“}'),
('philips-hue-de-4', 'hue', 'de', 4,                                                                                 'Licht-Kennung','Suchen Sie in der Hue-App nach der Light-ID oder dem Namen der Lampe. Damit identifizieren Sie die Lampe, die gesteuert werden soll.','{„light_id“: „ID oder Name der Lampe, die Sie steuern möchten. Diesen finden Sie in der Hue-App.“}'),
('philips-hue-de-5', 'hue', 'de', 5,                                                                                 'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um zu überprüfen, ob die Bridge reagiert und Ihr Token gültig ist.','{}');
                                                                                                                     
-- Insert LIFX guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('lifx-de-1', 'lifx', 'de', 1,                                                                                       'API-Schlüssel abrufen','Besuchen Sie https://cloud.lifx.com/settings und generieren Sie ein API-Token.','{}'),
('lifx-de-2', 'lifx', 'de', 2,                                                                                       'Token kopieren','Ihr persönlicher API-Token wird angezeigt. Kopieren Sie es – Sie werden es später nicht mehr sehen können!','{„api_key“: „Ihr persönliches LIFX-API-Token von https://cloud.lifx.com/settings“}'),
('lifx-de-3', 'lifx', 'de', 3,                                                                                       'Geräteauswahl finden','Suchen Sie in der LIFX-App oder unter https://cloud.lifx.com nach der Gerätebezeichnung oder -ID. Sie können „all“ verwenden, um alle Geräte zu steuern.','{„selector“: „LIFX-Geräteauswahl (Selector). Kann Gerätename, ID, Gruppenname oder 'all' sein. Beispiel: Living Room Light“}'),
('lifx-de-4', 'lifx', 'de', 4,                                                                                       'Zugangsdaten eingeben','Fügen Sie Ihr API-Token ein. Geben Sie die Gerätebezeichnung ein (z. B. „Living Room Light“ oder „all“).','{„api_key“: „Ihr persönliches LIFX-API-Token von https://cloud.lifx.com/settings“, „selector“: „LIFX-Geräteauswahl (Selector). Kann Gerätename, ID, Gruppenname oder 'all' sein. Beispiel: Living Room Light“}'),
('lifx-de-5', 'lifx', 'de', 5,                                                                                       'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um zu überprüfen, ob Token und Gerät erreichbar sind.','{}'); 
                                                                                                                      
-- Insert WiZ guides (English only for now)                                                                           
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES          
('wiz-de-1', 'wiz', 'de', 1,                                                                                         'Controller lokalisieren','Ermitteln Sie die IP-Adresse Ihres WiZ-Geräts in Ihrem lokalen Netzwerk. Überprüfen Sie dazu Ihren Router oder die WiZ-App.','{}'),
('wiz-de-2', 'wiz', 'de', 2,                                                                                         'Auth-Token abrufen','Verwenden Sie die WiZ-App, um ein API-Token oder einen Authentifizierungsschlüssel für den lokalen Zugriff zu generieren.','{„api_key“: „Authentifizierungs-Token für den lokalen API-Zugriff auf das WiZ-Gerät.“}'),
('wiz-de-3', 'wiz', 'de', 3,                                                                                         'IP & Token eingeben','Geben Sie die IP-Adresse Ihres WiZ-Geräts und das Authentifizierungs-Token ein.','{„device_ip“: „IP-Adresse Ihres WiZ-Geräts in Ihrem lokalen Netzwerk. Beispiel: 192.168.1.100“, „api_key“: „Authentifizierungs-Token für den lokalen API-Zugriff auf das WiZ-Gerät.“}'),
('wiz-de-4', 'wiz', 'de', 4,                                                                                         'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um zu überprüfen, ob das Gerät korrekt reagiert.','{}');
                                                                                                                                                                                                                                                                                     
-- Insert Nanoleaf guides (English only for now)                                                                                                                                                                                                                                     
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                         
('nanoleaf-de-1', 'nanoleaf', 'de', 1,                                                                               'Controller lokalisieren','Ermitteln Sie die IP-Adresse Ihres Nanoleaf-Controllers. Sie können diese über die Nanoleaf-App oder Ihren Router abrufen.','{}'),
('nanoleaf-de-2', 'nanoleaf', 'de', 2,                                                                               'API aktivieren','Das Nanoleaf-Gerät verfügt über eine lokal ausgeführte API. Sie benötigen lediglich dessen IP-Adresse und das Authentifizierungs-Token.','{}'),
('nanoleaf-de-3', 'nanoleaf', 'de', 3,                                                                               'Token generieren','Halten Sie die Ein-/Ausschalttaste 5 Sekunden lang gedrückt, bis sie pulsiert. Dadurch wird die API aktiviert. Generieren Sie anschließend ein Token mit dem Befehl: curl -X POST http://[IP]:[PORT]/api/v1/new','{"api_key": "Authentifizierungs-Token, das von Ihrem Nanoleaf-Gerät generiert wurde."}'),
('nanoleaf-de-4', 'nanoleaf', 'de', 4,                                                                               'Details eingeben','Geben Sie die IP-Adresse Ihres Nanoleaf-Geräts und das generierte Authentifizierungs-Token ein.','{"device_ip": "IP-Adresse Ihres Nanoleaf-Geräts im lokalen Netzwerk. Beispiel: 192.168.1.100", "api_key": "Authentifizierungs-Token, das von Ihrem Nanoleaf-Gerät generiert wurde."}'),
('nanoleaf-de-5', 'nanoleaf', 'de', 5,                                                                               'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um die lokale Verbindung zu Ihrem Gerät zu überprüfen.','{}');
                                                                                                                      
-- Insert TP-Link Kasa guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES          
('tp-link-kasa-de-1', 'kasa', 'de', 1,                                                                               'Geräte-IP finden','Verwenden Sie die Kasa-App oder überprüfen Sie Ihren Router, um die lokale IP-Adresse Ihres Geräts zu ermitteln.','{}'),
('tp-link-kasa-de-2', 'kasa', 'de', 2,                                                                               'Geräte-IP notieren','Das Kasa-Smart-Gerät nutzt eine lokale API. Sie benötigen lediglich dessen IP-Adresse im Netzwerk.','{}'),
('tp-link-kasa-de-3', 'kasa', 'de', 3,                                                                               'Lokalen Zugriff prüfen','Stellen Sie sicher, dass Ihr Portal-Server das Gerät erreichen kann. Geräte hinter einem VPN oder einer Firewall funktionieren möglicherweise nicht.','{}'),
('tp-link-kasa-de-4', 'kasa', 'de', 4,                                                                               'IP eingeben','Geben Sie die IP-Adresse Ihres Geräts im Format 192.168.1.50 ein.','{"device_ip": "IP-Adresse Ihres Kasa-Geräts im lokalen Netzwerk. Beispiel: 192.168.1.100"}'),
('tp-link-kasa-de-5', 'kasa', 'de', 5,                                                                               'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um zu überprüfen, ob Ihr Gerät erreichbar ist.','{}');
                                                                                                                      
-- Insert Yeelight guides (English only for now)                                                                      
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES          
('yeelight-de-1', 'yeelight', 'de', 1,                                                                               'Geräte-IP finden','Gehen Sie in der Yeelight-App zu den Geräteeinstellungen. Dort wird die IP-Adresse des Geräts angezeigt.','{}'),
('yeelight-de-2', 'yeelight', 'de', 2,                                                                               'Lokale Steuerung aktivieren','Stellen Sie in der Yeelight-App sicher, dass die Option „Local Network Control“ (Steuerung im lokalen Netzwerk) in den Geräteeinstellungen aktiviert ist.','{}'),
('yeelight-de-3', 'yeelight', 'de', 3,                                                                               'IP notieren','Kopieren Sie die Geräte-IP von der Einstellungsseite.','{"device_ip": "IP-Adresse Ihres Yeelight-Geräts im lokalen Netzwerk. Beispiel: 192.168.1.100"}'),
('yeelight-de-4', 'yeelight', 'de', 4,                                                                               'IP-Adresse eingeben','Geben Sie die IP-Adresse Ihres Yeelight-Geräts ein.','{"device_ip": "IP-Adresse Ihres Yeelight-Geräts im lokalen Netzwerk. Beispiel: 192.168.1.100"}'),
('yeelight-de-5', 'yeelight', 'de', 5,                                                                               'Verbindung testen','Klicken Sie auf „Test Credentials“ (Zugangsdaten testen), um zu überprüfen, ob Ihr Gerät im Netzwerk erreichbar ist.','{}');
                                                                                                                                                                                                                                                                                     
-- Insert WLED guides (English only for now)                                                                                                                                                                                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                         
('wled-de-1', 'wled', 'de', 1,                                                                                       'Geräte-IP finden','Verbinden Sie sich mit Ihrem WLED-Gerät. Die IP-Adresse finden Sie in Ihrem Router oder über die WLED-Weboberfläche.','{}'),
('wled-de-2', 'wled', 'de', 2,                                                                                       'Lokale Steuerung','WLED-Geräte nutzen eine lokale API. Normalerweise ist keine Authentifizierung erforderlich, lediglich die IP-Adresse des Geräts.','{}'),
('wled-de-3', 'wled', 'de', 3,                                                                                       'Zugriff testen','Stellen Sie sicher, dass Ihr Portal das Gerät erreichen kann (gleiches Netzwerk oder VPN).','{}'),
('wled-de-4', 'wled', 'de', 4,                                                                                       'IP eingeben','Geben Sie die IP-Adresse Ihres WLED-Geräts ein.','{"device_ip": "IP-Adresse Ihres WLED-Geräts im lokalen Netzwerk. Beispiel: 192.168.1.100"}'),
('wled-de-5', 'wled', 'de', 5,                                                                                       'Verbindung testen','Klicken Sie auf „Zugangsdaten testen“, um zu überprüfen, ob das Gerät reagiert.','{}');
                                                                                                                      
-- Insert Wyze guides (English only for now)                                                                          
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES          
('wyze-de-1', 'wyze', 'de', 1,                                                                                       'Nicht unterstützt','Die Wyze-Integration wird derzeit nicht über eine direkte API unterstützt. Wir prüfen derzeit OAuth-Optionen.','{}'),
('wyze-de-2', 'wyze', 'de', 2,                                                                                       'Weitere Infos','Informieren Sie sich später erneut über Updates zur Wyze-Unterstützung.','{}');
                                                                                                                      
-- Insert Amazon Alexa guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES          
('amazon-alexa-de-1', 'amazon', 'de', 1,                                                                             'Externe App','Die Amazon-Alexa-Integration nutzt einen externen Ablauf. Steuern Sie Ihre Alexa-Geräte über die offizielle Alexa-App.','{}'),
('amazon-alexa-de-2', 'amazon', 'de', 2,                                                                             'Demnächst verfügbar','Eine native Alexa-Integration ist für zukünftige Versionen geplant.','{}');

