-- Insert Govee guides (English only for now)
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES
('govee-ja-1', 'govee', 'ja', 1,                                                                                     'Goveeアプリを開く','iOSまたはAndroidスマートフォンでGoveeアプリを起動します。','{}'),
('govee-ja-2', 'govee', 'ja', 2,                                                                                     'APIキーを取得','「プロフィール」>「設定」>「APIキー」の順に進みます。キー全体（UUIDのような形式）をコピーします。これによりデバイスの認証が行われます。','{"api_key": "アプリ設定から取得できるGovee APIキー。すべてのAPIリクエストの認証に使用されます。"}'),
('govee-ja-3', 'govee', 'ja', 3,                                                                                     'デバイスを追加','Goveeアプリでデバイスを追加し、その名前を控えておきます。制御したいデバイスを特定するために必要になります。', '{}'),
('govee-ja-4', 'govee', 'ja', 4,                                                                                     '認証情報を入力','APIキーを貼り付けます。次に、デバイスのMACアドレスを入力します（アプリ内のデバイス情報で確認可能。形式：XX:XX:XX:XX:XX:XX）。','{"api_key": "アプリ設定から取得できるGovee APIキー。すべてのAPIリクエストの認証に使用されます。", "device_id": "GoveeデバイスのMACアドレス。Goveeアプリのデバイス情報ページで確認できます。形式: XX:XX:XX:XX:XX:XX"}'),
('govee-ja-5', 'govee', 'ja', 5,                                                                                     '接続をテスト','「Test Credentials（認証情報のテスト）」をクリックし、保存前に動作を確認します。','{}');
                                                                                                                     
-- Insert Philips Hue guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('philips-hue-ja-1', 'hue', 'ja', 1,                                                                                 'ブリッジを特定','ネットワークに接続されたHueブリッジ（物理ハブ）が必要です。お持ちでない場合は、入手する必要があります。','{}'),
('philips-hue-ja-2', 'hue', 'ja', 2,                                                                                 'ブリッジのIPアドレス','ルーターでブリッジのIPアドレスを確認します。「Philips Hue Bridge」という名前のデバイスを探すか、公式Hueアプリを使用して確認してください。','{"bridge_ip": "ネットワーク上のHue BridgeのIPアドレス。例: 192.168.1.50"}'),
('philips-hue-ja-3', 'hue', 'ja', 3,                                                                                 'トークンを生成','http://[BRIDGE_IP]/debug/clip.html にアクセスしてブリッジに接続します。ブリッジのボタンを押し、ユーザーを作成します。返されたユーザー名（これがAPIキーになります）をコピーします。','{"api_key": "Bridgeから生成されたAPIキー（ユーザー名）。Bridgeの設定から取得してください。"}'),
('philips-hue-ja-4', 'hue', 'ja', 4,                                                                                 'ライトの識別子','HueアプリでライトのIDまたは名前を確認します。これは制御するライトを特定するために使用します。','{"light_id": "制御したいライトのIDまたは名前。Hueアプリから取得してください。"}'),
('philips-hue-ja-5', 'hue', 'ja', 5,                                                                                 '接続をテスト','「Test Credentials（認証情報のテスト）」をクリックし、ブリッジが応答することとトークンが有効であることを確認します。','{}');
                                                                                                                     
-- Insert LIFX guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('lifx-ja-1', 'lifx', 'ja', 1,                                                                                       'APIキーを取得','https://cloud.lifx.com/settings にアクセスし、APIトークンを生成します。','{}'),
('lifx-ja-2', 'lifx', 'ja', 2,                                                                                       'トークンをコピー','個人のAPIトークンが表示されます。コピーしてください（二度と表示されません）。','{"api_key": "https://cloud.lifx.com/settings から取得できるLIFXの個人用APIトークン"}'),
('lifx-ja-3', 'lifx', 'ja', 3,                                                                                       'デバイス選択機能を探す','LIFXアプリまたは https://cloud.lifx.com で、デバイスのラベルまたはIDを確認します。「all」を使用してすべてのデバイスを制御することも可能です。','{"selector": "LIFXデバイスセレクター。デバイス名、ID、グループ名、または「all」を指定可能。例: Living Room Light"}'),
('lifx-ja-4', 'lifx', 'ja', 4,                                                                                       '認証情報を入力','APIトークンを貼り付けます。デバイスセレクター（例：「Living Room Light」や「all」）を入力します。','{"api_key": "https://cloud.lifx.com/settings から取得できるLIFXの個人用APIトークン", "selector": "LIFXデバイスセレクター。デバイス名、ID、グループ名、または「all」を指定可能。例: Living Room Light"}'),
('lifx-ja-5', 'lifx', 'ja', 5,                                                                                       '接続をテスト','「Test Credentials（認証情報のテスト）」をクリックし、トークンとデバイスにアクセスできることを確認します。','{}');
                                                                                                                     
-- Insert WiZ guides (English only for now)                                                                          
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('wiz-ja-1', 'wiz', 'ja', 1,                                                                                         'コントローラーを特定','ローカルネットワーク上でWiZデバイスのIPアドレスを確認します。ルーターまたはWiZアプリで確認してください。', '{}'),
('wiz-ja-2', 'wiz', 'ja', 2,                                                                                         '認証トークンを取得','WiZアプリを使用して、ローカルアクセス用のAPIトークンまたは認証キーを生成します。','{"api_key": "WiZデバイスのローカルAPIアクセス用認証トークン。"}'),
('wiz-ja-3', 'wiz', 'ja', 3,                                                                                         'IPとトークンを入力','WiZデバイスのIPアドレスと認証トークンを入力します。','{"device_ip": "ローカルネットワーク上のWiZデバイスのIPアドレス。例: 192.168.1.100", "api_key": "WiZデバイスのローカルAPIアクセス用認証トークン。"}'),
('wiz-ja-4', 'wiz', 'ja', 4,                                                                                         '接続をテスト','「Test Credentials（認証情報のテスト）」をクリックし、デバイスが正しく応答することを確認します。', '{}');
                                                                                                                                                                                                                                                                                    
-- Insert Nanoleaf guides (English only for now)                                                                                                                                                                                                                                    
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('nanoleaf-ja-1', 'nanoleaf', 'ja', 1,                                                                               'コントローラーを特定','NanoleafコントローラーのIPアドレスを確認してください。Nanoleafアプリまたはルーターから確認できます。','{}'),
('nanoleaf-ja-2', 'nanoleaf', 'ja', 2,                                                                               'APIを有効化','NanoleafデバイスはローカルでAPIを動作させています。必要なのはIPアドレスと認証トークンだけです。','{}'),
('nanoleaf-ja-3', 'nanoleaf', 'ja', 3,                                                                               'トークンを生成','電源ボタンを5秒間長押しし、ライトが点滅（パルス）し始めたら離します。これでAPIが有効になります。次に、以下のコマンドでトークンを生成してください：curl -X POST http://[IP]:[PORT]/api/v1/new','{"api_key": "Nanoleafデバイスで生成された認証トークン。"}'),
('nanoleaf-ja-4', 'nanoleaf', 'ja', 4,                                                                               '詳細を入力','NanoleafデバイスのIPアドレスと、生成した認証トークンを入力してください。','{"device_ip": "ローカルネットワーク上のNanoleafデバイスのIPアドレス。例: 192.168.1.100", "api_key": "Nanoleafデバイスで生成された認証トークン。"}'),
('nanoleaf-ja-5', 'nanoleaf', 'ja', 5,                                                                               '接続をテスト','"Test Credentials"（認証情報のテスト）をクリックして、デバイスへのローカル接続を確認してください。','{}');
                                                                                                                     
-- Insert TP-Link Kasa guides (English only for now)                                                                 
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('tp-link-kasa-ja-1', 'kasa', 'ja', 1,                                                                               'デバイスのIPを特定','Kasaアプリを使用するか、ルーターを確認して、デバイスのローカルIPアドレスを調べてください。','{}'),
('tp-link-kasa-ja-2', 'kasa', 'ja', 2,                                                                               'デバイスのIPを控える','KasaスマートデバイスはローカルAPIを動作させています。ネットワーク上のIPアドレスさえあれば利用可能です。','{}'),
('tp-link-kasa-ja-3', 'kasa', 'ja', 3,                                                                               'ローカルアクセスを確認','ポータルサーバーからデバイスにアクセスできることを確認してください。VPNやファイアウォールの内側にあるデバイスは動作しない場合があります。','{}'),
('tp-link-kasa-ja-4', 'kasa', 'ja', 4,                                                                               'IPを入力','デバイスのIPアドレスを「192.168.1.50」のような形式で入力してください。','{"device_ip": "ローカルネットワーク上のKasaデバイスのIPアドレス。例: 192.168.1.100"}'),
('tp-link-kasa-ja-5', 'kasa', 'ja', 5,                                                                               '接続をテスト','"Test Credentials"（認証情報のテスト）をクリックして、デバイスにアクセスできるか確認してください。','{}');
                                                                                                                     
-- Insert Yeelight guides (English only for now)                                                                     
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('yeelight-ja-1', 'yeelight', 'ja', 1,                                                                               'デバイスのIPを特定','Yeelightアプリで「デバイス設定」に移動すると、デバイスのIPアドレスが表示されます。','{}'),
('yeelight-ja-2', 'yeelight', 'ja', 2,                                                                               'ローカル制御を有効化','Yeelightアプリのデバイス設定で、「ローカルネットワーク制御（Local Network Control）」が有効になっていることを確認してください。','{}'),
('yeelight-ja-3', 'yeelight', 'ja', 3,                                                                               'IPを控える','設定ページからデバイスのIPアドレスをコピーしてください。','{"device_ip": "ローカルネットワーク上のYeelightデバイスのIPアドレス。例: 192.168.1.100"}'),
('yeelight-ja-4', 'yeelight', 'ja', 4,                                                                               'IPアドレスを入力','YeelightデバイスのIPアドレスを入力してください。','{"device_ip": "ローカルネットワーク上のYeelightデバイスのIPアドレス。例: 192.168.1.100"}'),
('yeelight-ja-5', 'yeelight', 'ja', 5,                                                                               '接続をテスト','"Test Credentials"（認証情報のテスト）をクリックして、ネットワーク上でデバイスにアクセスできるか確認してください。','{}');
                                                                                                                     
-- Insert WLED guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('wled-ja-1', 'wled', 'ja', 1,                                                                                       'デバイスのIPを特定','WLEDデバイスに接続します。IPアドレスはルーターまたはWLEDのWebインターフェースで確認できます。','{}'),
('wled-ja-2', 'wled', 'ja', 2,                                                                                       'ローカル制御','WLEDデバイスはローカルAPIを動作させています。通常、認証は不要で、デバイスのIPアドレスのみが必要です。','{}'),
('wled-ja-3', 'wled', 'ja', 3,                                                                                       'アクセスをテスト','ポータルからデバイスにアクセスできることを確認してください（同一ネットワークまたはVPN接続）。','{}'),
('wled-ja-4', 'wled', 'ja', 4,                                                                                       'IPを入力','WLEDデバイスのIPアドレスを入力してください。','{"device_ip": "ローカルネットワーク上のWLEDデバイスのIPアドレス。例: 192.168.1.100"}'),
('wled-ja-5', 'wled', 'ja', 5,                                                                                       '接続をテスト','"Test Credentials"（認証情報のテスト）をクリックして、デバイスが応答することを確認してください。','{}');
                                                                                                                                                                                                                                                                                    
-- Insert Wyze guides (English only for now)                                                                                                                                                                                                                                        
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('wyze-ja-1', 'wyze', 'ja', 1,                                                                                       '非対応','現在、Wyzeとの直接API連携には対応しておりません。OAuthを利用した連携方法について検討中です。'                                                          ,'{}'),
('wyze-ja-2', 'wyze', 'ja', 2,                                                                                       '詳細情報','Wyzeのサポートに関する最新情報は、後ほどご確認ください。'                                                                                                                ,'{}');
                                                                                                                                                                                                                                                                                    
-- Insert Amazon Alexa guides (English only for now)                                                                                                                                                                                                                                
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('amazon-alexa-ja-1', 'amazon', 'ja', 1,                                                                             '外部アプリ','Amazon Alexaとの連携には、外部フローを使用します。Alexaデバイスの操作は、公式のAlexaアプリから行ってください。'                                                   ,'{}'),
('amazon-alexa-ja-2', 'amazon', 'ja', 2,                                                                             '近日公開','将来のリリースで、Alexaとのネイティブ連携が予定されています。'                                                                                                     ,'{}');
