-- Insert Govee guides (English only for now)
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES
('govee-fr-1', 'govee', 'fr', 1,                                                                                     'Ouvrir l′application Govee','Lancez l′application Govee sur votre téléphone iOS ou Android.','{}'),
('govee-fr-2', 'govee', 'fr', 2,                                                                                     'Obtenir la clé API','Allez dans Profil > Paramètres > Clé API. Copiez la clé complète (elle ressemble à un UUID). Cela permet d′authentifier vos appareils.','{"api_key": "Votre clé API Govee issue des paramètres de l′application. Utilisée pour authentifier toutes les requêtes API."}'),
('govee-fr-3', 'govee', 'fr', 3,                                                                                     'Ajouter un appareil','Dans l′application Govee, ajoutez vos appareils et notez leurs noms. Vous devrez identifier l′appareil que vous souhaitez contrôler.', '{}'),
('govee-fr-4', 'govee', 'fr', 4,                                                                                     'Saisir les identifiants','Collez votre clé API. Saisissez ensuite l′adresse MAC de l′appareil (disponible dans les informations de l′appareil dans l′application, au format : XX:XX:XX:XX:XX:XX).','{"api_key": "Votre clé API Govee issue des paramètres de l′application. Utilisée pour authentifier toutes les requêtes API.", "device_id": "L′adresse MAC de votre appareil Govee. Disponible sur la page d′informations de l′appareil dans l′application Govee. Format : XX:XX:XX:XX:XX:XX"}'),
('govee-fr-5', 'govee', 'fr', 5,                                                                                     'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que tout fonctionne avant d′enregistrer.','{}');
                                                                                                                     
-- Insert Philips Hue guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('philips-hue-fr-1', 'hue', 'fr', 1,                                                                                 'Localiser le pont','Vous avez besoin d′un pont Hue (hub physique) connecté à votre réseau. Si vous n′en avez pas, vous devrez vous en procurer un.','{}'),
('philips-hue-fr-2', 'hue', 'fr', 2,                                                                                 'Adresse IP du pont','Trouvez l′adresse IP de votre pont sur votre routeur. Cherchez un appareil nommé « Philips Hue Bridge » ou utilisez l′application officielle Hue pour le localiser.','{"bridge_ip": "Adresse IP de votre pont Hue sur votre réseau. Exemple : 192.168.1.50"}'),
('philips-hue-fr-3', 'hue', 'fr', 3,                                                                                 'Générer un jeton','Accédez au pont via l′adresse http://[BRIDGE_IP]/debug/clip.html. Appuyez sur le bouton du pont, puis créez un utilisateur. Copiez le nom d′utilisateur renvoyé (il s′agit de votre clé API).','{"api_key": "Clé API générée par le pont (nom d′utilisateur). Disponible dans les paramètres du pont."}'),
('philips-hue-fr-4', 'hue', 'fr', 4,                                                                                 'Identifiant de la lumière','Dans l′application Hue, trouvez l′ID ou le nom de la lampe. Vous l′utiliserez pour identifier la lampe à contrôler.','{"light_id": "ID ou nom de la lumière que vous souhaitez contrôler. Disponible dans l′application Hue."}'),
('philips-hue-fr-5', 'hue', 'fr', 5,                                                                                 'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que le pont répond et que votre jeton est valide.','{}');
                                                                                                                     
-- Insert LIFX guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('lifx-fr-1', 'lifx', 'fr', 1,                                                                                       'Obtenir la clé API','Rendez-vous sur https://cloud.lifx.com/settings et générez un jeton API.','{}'),
('lifx-fr-2', 'lifx', 'fr', 2,                                                                                       'Copier le jeton','Votre jeton API personnel s′affichera. Copiez-le ; il ne sera plus visible par la suite !','{"api_key": "Votre jeton API personnel LIFX obtenu sur https://cloud.lifx.com/settings"}'),
('lifx-fr-3', 'lifx', 'fr', 3,                                                                                       'Trouver le sélecteur d′appareil','Dans l′application LIFX ou sur https://cloud.lifx.com, trouvez le nom ou l′ID de votre appareil. Vous pouvez utiliser « all » pour contrôler tous les appareils.','{"selector": "Sélecteur d′appareil LIFX. Peut être le nom de l′appareil, l′ID, le nom du groupe ou "all" (tous). Exemple : Living Room Light"}'),
('lifx-fr-4', 'lifx', 'fr', 4,                                                                                       'Saisir les identifiants','Collez votre jeton API. Saisissez le sélecteur de votre appareil (par ex. « Living Room Light » ou « all »).','{"api_key": "Votre jeton API personnel LIFX obtenu sur https://cloud.lifx.com/settings", "selector": "Sélecteur d′appareil LIFX. Peut être le nom de l′appareil, l′ID, le nom du groupe ou "all" (tous). Exemple : Living Room Light"}'),
('lifx-fr-5', 'lifx', 'fr', 5,                                                                                       'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que votre jeton et votre appareil sont accessibles.','{}');
                                                                                                                     
-- Insert WiZ guides (English only for now)                                                                          
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('wiz-fr-1', 'wiz', 'fr', 1,                                                                                         'Localiser le contrôleur','Trouvez l′adresse IP de votre appareil WiZ sur votre réseau local. Consultez votre routeur ou l′application WiZ.', '{}'),
('wiz-fr-2', 'wiz', 'fr', 2,                                                                                         'Obtenir le jeton d′authentification','Utilisez l′application WiZ pour générer un jeton API ou une clé d′authentification pour un accès local.','{"api_key": "Jeton d′authentification pour l′accès à l′API locale de l′appareil WiZ."}'),
('wiz-fr-3', 'wiz', 'fr', 3,                                                                                         'Saisir l′IP et le jeton','Saisissez l′adresse IP de votre appareil WiZ et le jeton d′authentification.','{"device_ip": "Adresse IP de votre appareil WiZ sur votre réseau local. Exemple : 192.168.1.100", "api_key": "Jeton d′authentification pour l′accès à l′API locale de l′appareil WiZ."}'),
('wiz-fr-4', 'wiz', 'fr', 4,                                                                                         'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que l′appareil répond correctement.', '{}');
                                                                                                                                                                                                                                                                                    
-- Insert Nanoleaf guides (English only for now)                                                                                                                                                                                                                                    
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('nanoleaf-fr-1', 'nanoleaf', 'fr', 1,                                                                               'Localiser le contrôleur','Trouvez l′adresse IP de votre contrôleur Nanoleaf. Accédez-y via l′application Nanoleaf ou votre routeur.','{}'),
('nanoleaf-fr-2', 'nanoleaf', 'fr', 2,                                                                               'Activer l′API','L′appareil Nanoleaf exécute une API en local. Il vous suffit de connaître son adresse IP et son jeton d′authentification.','{}'),
('nanoleaf-fr-3', 'nanoleaf', 'fr', 3,                                                                               'Générer un jeton','Maintenez le bouton d′alimentation enfoncé pendant 5 secondes jusqu′à ce qu′il clignote. Cela active l′API. Générez ensuite un jeton à l′aide de la commande : curl -X POST http://[IP]:[PORT]/api/v1/new','{"api_key": "Jeton d′authentification généré par votre appareil Nanoleaf."}'),
('nanoleaf-fr-4', 'nanoleaf', 'fr', 4,                                                                               'Saisir les informations','Saisissez l′adresse IP de votre appareil Nanoleaf et le jeton d′authentification que vous avez généré.','{"device_ip": "Adresse IP de votre appareil Nanoleaf sur votre réseau local. Exemple : 192.168.1.100", "api_key": "Jeton d′authentification généré par votre appareil Nanoleaf."}'),
('nanoleaf-fr-5', 'nanoleaf', 'fr', 5,                                                                               'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier la connexion locale à votre appareil.','{}');
                                                                                                                     
-- Insert TP-Link Kasa guides (English only for now)                                                                 
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('tp-link-kasa-fr-1', 'kasa', 'fr', 1,                                                                               'Trouver l′IP de l′appareil','Utilisez l′application Kasa ou consultez votre routeur pour trouver l′adresse IP locale de votre appareil.','{}'),
('tp-link-kasa-fr-2', 'kasa', 'fr', 2,                                                                               'Noter l′IP de l′appareil','L′appareil intelligent Kasa utilise une API locale. Vous avez uniquement besoin de son adresse IP sur votre réseau.','{}'),
('tp-link-kasa-fr-3', 'kasa', 'fr', 3,                                                                               'Vérifier l′accès local','Assurez-vous que votre serveur portail peut atteindre l′appareil. Les appareils situés derrière un VPN ou un pare-feu pourraient ne pas fonctionner.','{}'),
('tp-link-kasa-fr-4', 'kasa', 'fr', 4,                                                                               'Saisir l′IP','Saisissez l′adresse IP de votre appareil au format : 192.168.1.50','{"device_ip": "Adresse IP de votre appareil Kasa sur votre réseau local. Exemple : 192.168.1.100"}'),
('tp-link-kasa-fr-5', 'kasa', 'fr', 5,                                                                               'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que votre appareil est joignable.','{}');
                                                                                                                     
-- Insert Yeelight guides (English only for now)                                                                     
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('yeelight-fr-1', 'yeelight', 'fr', 1,                                                                               'Trouver l′IP de l′appareil','Dans l′application Yeelight, accédez aux paramètres de l′appareil. Vous y verrez l′adresse IP de l′appareil.','{}'),
('yeelight-fr-2', 'yeelight', 'fr', 2,                                                                               'Activer le contrôle local','Dans l′application Yeelight, assurez-vous que l′option « Contrôle du réseau local » est activée dans les paramètres de l′appareil.','{}'),
('yeelight-fr-3', 'yeelight', 'fr', 3,                                                                               'Noter l′IP','Copiez l′adresse IP de l′appareil depuis la page des paramètres.','{"device_ip": "Adresse IP de votre appareil Yeelight sur votre réseau local. Exemple : 192.168.1.100"}'),
('yeelight-fr-4', 'yeelight', 'fr', 4,                                                                               'Saisir l′adresse IP','Saisissez l′adresse IP de votre appareil Yeelight.','{"device_ip": "Adresse IP de votre appareil Yeelight sur votre réseau local. Exemple : 192.168.1.100"}'),
('yeelight-fr-5', 'yeelight', 'fr', 5,                                                                               'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que votre appareil est joignable sur le réseau.','{}');
                                                                                                                                                                                                                                                                                    
-- Insert WLED guides (English only for now)                                                                                                                                                                                                                                        
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('wled-fr-1', 'wled', 'fr', 1,                                                                                       'Trouver l′IP de l′appareil','Connectez-vous à votre appareil WLED. Vous pouvez trouver son adresse IP dans les paramètres de votre routeur ou via l′interface web de WLED.','{}'),
('wled-fr-2', 'wled', 'fr', 2,                                                                                       'Contrôle local','Les appareils WLED utilisent une API locale. Aucune authentification n′est généralement requise ; seule l′adresse IP de l′appareil est nécessaire.','{}'),
('wled-fr-3', 'wled', 'fr', 3,                                                                                       'Tester l′accès','Assurez-vous que votre portail peut accéder à l′appareil (via le même réseau ou un VPN).','{}'),
('wled-fr-4', 'wled', 'fr', 4,                                                                                       'Saisir l′IP','Saisissez l′adresse IP de votre appareil WLED.','{"device_ip": "Adresse IP de votre appareil WLED sur votre réseau local. Exemple : 192.168.1.100"}'),
('wled-fr-5', 'wled', 'fr', 5,                                                                                       'Tester la connexion','Cliquez sur « Tester les identifiants » pour vérifier que l′appareil répond.','{}');
                                                                                                                     
-- Insert Wyze guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('wyze-fr-1', 'wyze', 'fr', 1,                                                                                       'Non pris en charge','L′intégration Wyze n′est actuellement pas prise en charge via une API directe. Nous étudions des options basées sur OAuth.','{}'),
('wyze-fr-2', 'wyze', 'fr', 2,                                                                                       'Plus d′infos','Revenez plus tard pour des mises à jour concernant la prise en charge de Wyze.','{}');
                                                                                                                     
-- Insert Amazon Alexa guides (English only for now)                                                                 
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('amazon-alexa-fr-1', 'amazon', 'fr', 1,                                                                             'Application externe','L′intégration d′Amazon Alexa repose sur un processus externe. Contrôlez vos appareils Alexa via l′application officielle Alexa.','{}'),
('amazon-alexa-fr-2', 'amazon', 'fr', 2,                                                                             'Bientôt disponible','Une intégration native d′Alexa est prévue pour de futures versions.','{}');
