-- Insert Govee guides (English only for now)
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES
('govee-es-1', 'govee', 'es', 1,                                                                                     'Abrir la aplicación Govee','Abre la aplicación Govee en tu teléfono iOS o Android.','{}'),
('govee-es-2', 'govee', 'es', 2,                                                                                     'Obtener clave API','Ve a Perfil > Configuración > Clave API. Copia la clave completa (tiene el formato de un UUID). Esto autentica tus dispositivos.','{"api_key": "Tu clave API de Govee obtenida en la configuración de la aplicación. Se utiliza para autenticar todas las solicitudes a la API."}'),
('govee-es-3', 'govee', 'es', 3,                                                                                     'Añadir dispositivo','En la aplicación Govee, añade tus dispositivos y anota sus nombres. Necesitarás identificar qué dispositivo quieres controlar.', '{}'),
('govee-es-4', 'govee', 'es', 4,                                                                                     'Introducir credenciales','Pega tu clave API. Luego, introduce la dirección MAC del dispositivo (que encontrarás en la información del dispositivo dentro de la aplicación; formato: XX:XX:XX:XX:XX:XX).','{"api_key": "Tu clave API de Govee obtenida en la configuración de la aplicación. Se utiliza para autenticar todas las solicitudes a la API.", "device_id": "La dirección MAC de tu dispositivo Govee. Se encuentra en la página de información del dispositivo dentro de la aplicación Govee. Formato: XX:XX:XX:XX:XX:XX"}'),
('govee-es-5', 'govee', 'es', 5,                                                                                     'Probar conexión','Haz clic en "Probar credenciales" para verificar que todo funciona antes de guardar.','{}');
                                                                                                                     
-- Insert Philips Hue guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('philips-hue-es-1', 'hue', 'es', 1,                                                                                 'Localizar puente','Necesitas un Hue Bridge (concentrador físico) conectado a tu red. Si no tienes uno, deberás conseguirlo.','{}'),
('philips-hue-es-2', 'hue', 'es', 2,                                                                                 'Dirección IP del puente','Localiza la dirección IP de tu Bridge en el router. Busca un dispositivo llamado "Philips Hue Bridge" o utiliza la aplicación oficial de Hue para encontrarlo.','{"bridge_ip": "Dirección IP de tu Hue Bridge en la red. Ejemplo: 192.168.1.50"}'),
('philips-hue-es-3', 'hue', 'es', 3,                                                                                 'Generar token','Accede al Bridge en http://[BRIDGE_IP]/debug/clip.html. Pulsa el botón del Bridge y crea un usuario. Copia el nombre de usuario resultante (esta es tu clave API).','{"api_key": "Clave API generada desde el Bridge (nombre de usuario). Consíguela en la configuración del Bridge."}'),
('philips-hue-es-4', 'hue', 'es', 4,                                                                                 'Identificador de la luz','En la aplicación Hue, busca el ID o el nombre de la luz. Lo utilizarás para identificar qué luz controlar.','{"light_id": "ID o nombre de la luz que deseas controlar. Consíguelo en la aplicación Hue."}'),
('philips-hue-es-5', 'hue', 'es', 5,                                                                                 'Probar conexión','Haz clic en "Probar credenciales" para verificar que el Bridge responde y que tu token es válido.','{}');
                                                                                                                     
-- Insert LIFX guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('lifx-es-1', 'lifx', 'es', 1,                                                                                       'Obtener clave API','Visita https://cloud.lifx.com/settings y genera un token API.','{}'),
('lifx-es-2', 'lifx', 'es', 2,                                                                                       'Copiar token','Se mostrará tu token API personal. ¡Cópialo, ya que no volverás a verlo!','{"api_key": "Tu token personal de API de LIFX obtenido en https://cloud.lifx.com/settings"}'),
('lifx-es-3', 'lifx', 'es', 3,                                                                                       'Buscar selector de dispositivo','En la aplicación LIFX o en https://cloud.lifx.com, busca la etiqueta o el ID de tu dispositivo. Puedes usar "all" para controlar todos los dispositivos.','{"selector": "Selector de dispositivo LIFX. Puede ser el nombre del dispositivo, el ID, el nombre del grupo o 'all' (todos). Ejemplo: Living Room Light"}'),
('lifx-es-4', 'lifx', 'es', 4,                                                                                       'Introducir credenciales','Pega tu token API. Introduce el selector de dispositivo (p. ej., "Living Room Light" o "all").','{"api_key": "Tu token personal de API de LIFX obtenido en https://cloud.lifx.com/settings", "selector": "Selector de dispositivo LIFX. Puede ser el nombre del dispositivo, el ID, el nombre del grupo o 'all' (todos). Ejemplo: Living Room Light"}'),
('lifx-es-5', 'lifx', 'es', 5,                                                                                       'Probar conexión','Haz clic en "Probar credenciales" para verificar que el token y el dispositivo son accesibles.','{}');
                                                                                                                     
-- Insert WiZ guides (English only for now)                                                                          
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('wiz-es-1', 'wiz', 'es', 1,                                                                                         'Localizar controlador','Localiza la dirección IP de tu dispositivo WiZ en la red local. Consulta el router o la aplicación WiZ.', '{}'),
('wiz-es-2', 'wiz', 'es', 2,                                                                                         'Obtener token de autenticación','Utiliza la aplicación WiZ para generar un token API o una clave de autenticación para el acceso local.','{"api_key": "Token de autenticación para el acceso a la API local del dispositivo WiZ."}'),
('wiz-es-3', 'wiz', 'es', 3,                                                                                         'Introducir IP y token','Introduce la dirección IP de tu dispositivo WiZ y el token de autenticación.','{"device_ip": "Dirección IP de tu dispositivo WiZ en la red local. Ejemplo: 192.168.1.100", "api_key": "Token de autenticación para el acceso a la API local del dispositivo WiZ."}'),
('wiz-es-4', 'wiz', 'es', 4,                                                                                         'Probar conexión','Haz clic en "Probar credenciales" para verificar que el dispositivo responde correctamente.', '{}');
                                                                                                                                                                                                                                                                                    
-- Insert Nanoleaf guides (English only for now)                                                                                                                                                                                                                                    
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('nanoleaf-es-1', 'nanoleaf', 'es', 1,                                                                               'Localizar controlador','Busca la dirección IP de tu controlador Nanoleaf. Accede a ella a través de la aplicación Nanoleaf o de tu router.','{}'),
('nanoleaf-es-2', 'nanoleaf', 'es', 2,                                                                               'Activar API','El dispositivo Nanoleaf ejecuta una API de forma local. Solo necesitas su dirección IP y el token de autenticación.','{}'),
('nanoleaf-es-3', 'nanoleaf', 'es', 3,                                                                               'Generar token','Mantén pulsado el botón de encendido durante 5 segundos hasta que parpadee. Esto activa la API. Luego, genera un token usando: curl -X POST http://[IP]:[PUERTO]/api/v1/new','{"api_key": "Token de autenticación generado desde tu dispositivo Nanoleaf."}'),
('nanoleaf-es-4', 'nanoleaf', 'es', 4,                                                                               'Introducir detalles','Introduce la dirección IP de tu dispositivo Nanoleaf y el token de autenticación que has generado.','{"device_ip": "Dirección IP de tu dispositivo Nanoleaf en tu red local. Ejemplo: 192.168.1.100", "api_key": "Token de autenticación generado desde tu dispositivo Nanoleaf."}'),
('nanoleaf-es-5', 'nanoleaf', 'es', 5,                                                                               'Probar conexión','Haz clic en "Probar credenciales" para verificar la conexión local con tu dispositivo.','{}');
                                                                                                                     
-- Insert TP-Link Kasa guides (English only for now)                                                                 
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('tp-link-kasa-es-1', 'kasa', 'es', 1,                                                                               'Buscar IP del dispositivo','Usa la aplicación Kasa o consulta tu router para encontrar la dirección IP local de tu dispositivo.','{}'),
('tp-link-kasa-es-2', 'kasa', 'es', 2,                                                                               'Anotar IP del dispositivo','El dispositivo inteligente Kasa ejecuta una API local. Solo necesitas su dirección IP en tu red.','{}'),
('tp-link-kasa-es-3', 'kasa', 'es', 3,                                                                               'Verificar acceso local','Asegúrate de que tu servidor de portal pueda comunicarse con el dispositivo. Es posible que los dispositivos detrás de una VPN o un cortafuegos no funcionen.','{}'),
('tp-link-kasa-es-4', 'kasa', 'es', 4,                                                                               'Introducir IP','Introduce la dirección IP de tu dispositivo con el formato: 192.168.1.50','{"device_ip": "Dirección IP de tu dispositivo Kasa en tu red local. Ejemplo: 192.168.1.100"}'),
('tp-link-kasa-es-5', 'kasa', 'es', 5,                                                                               'Probar conexión','Haz clic en "Probar credenciales" para verificar que se puede acceder al dispositivo.','{}');
                                                                                                                     
-- Insert Yeelight guides (English only for now)                                                                     
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('yeelight-es-1', 'yeelight', 'es', 1,                                                                               'Buscar IP del dispositivo','En la aplicación Yeelight, ve a la configuración del dispositivo. Verás la dirección IP del dispositivo.','{}'),
('yeelight-es-2', 'yeelight', 'es', 2,                                                                               'Activar control local','En la aplicación Yeelight, asegúrate de que la opción "Control de red local" esté activada en la configuración del dispositivo.','{}'),
('yeelight-es-3', 'yeelight', 'es', 3,                                                                               'Anotar la IP','Copia la dirección IP del dispositivo desde la página de configuración.','{"device_ip": "Dirección IP de tu dispositivo Yeelight en tu red local. Ejemplo: 192.168.1.100"}'),
('yeelight-es-4', 'yeelight', 'es', 4,                                                                               'Introducir dirección IP','Introduce la dirección IP de tu dispositivo Yeelight.','{"device_ip": "Dirección IP de tu dispositivo Yeelight en tu red local. Ejemplo: 192.168.1.100"}'),
('yeelight-es-5', 'yeelight', 'es', 5,                                                                               'Probar conexión','Haz clic en "Probar credenciales" para verificar que se puede acceder al dispositivo en la red.','{}');
                                                                                                                                                                                                                                                                                    
-- Insert WLED guides (English only for now)                                                                                                                                                                                                                                        
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('wled-es-1', 'wled', 'es', 1,                                                                                       'Buscar IP del dispositivo','Conéctate a tu dispositivo WLED. Puedes encontrar la dirección IP en tu router o a través de la interfaz web de WLED.','{}'),
('wled-es-2', 'wled', 'es', 2,                                                                                       'Control local','Los dispositivos WLED ejecutan una API local. Por lo general, no se requiere autenticación, basta con la dirección IP del dispositivo.','{}'),
('wled-es-3', 'wled', 'es', 3,                                                                                       'Probar acceso','Asegúrate de que tu portal pueda comunicarse con el dispositivo (misma red o VPN).','{}'),
('wled-es-4', 'wled', 'es', 4,                                                                                       'Introducir IP','Introduce la dirección IP de tu dispositivo WLED.','{"device_ip": "Dirección IP de tu dispositivo WLED en tu red local. Ejemplo: 192.168.1.100"}'),
('wled-es-5', 'wled', 'es', 5,                                                                                       'Probar conexión','Haz clic en "Probar credenciales" para verificar que el dispositivo responde.','{}');
                                                                                                                     
-- Insert Wyze guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('wyze-es-1', 'wyze', 'es', 1,                                                                                       'No compatible','Actualmente no se admite la integración con Wyze mediante API directa. Estamos investigando opciones de OAuth.','{}'),
('wyze-es-2', 'wyze', 'es', 2,                                                                                       'Más información','Consulta más adelante si hay novedades sobre la compatibilidad con Wyze.','{}');
                                                                                                                     
-- Insert Amazon Alexa guides (English only for now)                                                                 
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('amazon-alexa-es-1', 'amazon', 'es', 1,                                                                             'Aplicación externa','La integración con Amazon Alexa utiliza un flujo externo. Controla tus dispositivos Alexa a través de la aplicación oficial de Alexa.','{}'),
('amazon-alexa-es-2', 'amazon', 'es', 2,                                                                             'Próximamente','Está prevista una integración nativa con Alexa para futuras versiones.','{}');
