-- Insert Govee guides (English only for now)
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES
('govee-zh-1', 'govee', 'zh', 1,                                                                                     '開啟 Govee App','在您的 iOS 或 Android 手機上啟動 Govee 應用程式。','{}'),
('govee-zh-2', 'govee', 'zh', 2,                                                                                     '取得 API 金鑰','前往「個人資料」>「設定」>「API 金鑰」。複製完整的金鑰（看起來像一個 UUID）。這將驗證您的裝置。','{"api_key": "您在應用程式設定中取得的 Govee API 金鑰。用於驗證所有 API 請求。"}'),
('govee-zh-3', 'govee', 'zh', 3,                                                                                     '新增設備','在 Govee 應用程式中，新增您的裝置並記下它們的名稱。您需要確定要控制哪個設備。','{}'),
('govee-zh-4', 'govee', 'zh', 4,                                                                                     '輸入憑證','貼上您的 API 金鑰。然後輸入設備的 MAC 位址（可在套用的設備資訊中找到，格式為：XX:XX:XX:XX:XX:XX）。','{"api_key": "您在應用程式設定中取得的 Govee API 金鑰。用於驗證所有 API 要求。", "device_id": "您的 Govee 裝置的 MAC 位址。可在 Govee 應用程式的裝置資訊頁面中找到。格式：XX:XX:XX:XX:XX:XX"}'),
('govee-zh-5', 'govee', 'zh', 5,                                                                                     '測試連接','點擊「測試憑證」以驗證一切是否正常運作，然後再儲存。','{}');
                                                                                                                     
-- Insert Philips Hue guides (English only for now)                                                                  
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('philips-hue-zh-1', 'hue', 'zh', 1,                                                                                 '找網橋','您需要一個連接到網路的 Hue Bridge（實體集線器）。如果您沒有，則需要購買一個。','{}'),
('philips-hue-zh-2', 'hue', 'zh', 2,                                                                                 '橋接 IP 位址','在您的路由器上找到 Bridge 的 IP 位址。尋找名為「Philips Hue Bridge」的設備，或使用官方 Hue 應用程式尋找。','{"bridge_ip": "您網路中 Hue 橋接器的 IP 位址。例如：192.168.1.50"}'),
('philips-hue-zh-3', 'hue', 'zh', 3,                                                                                 '產生令牌','請造訪 http://[BRIDGE_IP]/debug/clip.html 上的 Bridge。按下橋接按鈕，然後建立一個使用者。複製傳回的使用者名稱（這就是您的 API 金鑰）。','{"api_key": "由網橋（使用者名稱）產生的 API 金鑰。請從網橋設定中取得。"}'),
('philips-hue-zh-4', 'hue', 'zh', 4,                                                                                 '燈光標識符','在 Hue 應用程式中，找到燈具 ID 或名稱。您將使用它來識別要控制的燈具。','{"light_id": "您要控制的燈的 ID 或名稱。請從 Hue 應用中取得。"}'),
('philips-hue-zh-5', 'hue', 'zh', 5,                                                                                 '測試連接','點擊“測試憑證”以驗證橋接器是否回應以及您的令牌是否有效。','{}');
                                                                                                                     
-- Insert LIFX guides (English only for now)                                                                         
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         
('lifx-zh-1', 'lifx', 'zh', 1,                                                                                       '取得 API 金鑰','造訪 https://cloud.lifx.com/settings 並產生 API 令牌。','{}'),
('lifx-zh-2', 'lifx', 'zh', 2,                                                                                       '複製令牌','您的個人 API 令牌將顯示在此。請複製它——您將不會再次看到它！','{"api_key": "您的 LIFX 個人 API 令牌，來自 https://cloud.lifx.com/settings"}'),
('lifx-zh-3', 'lifx', 'zh', 3,                                                                                       '尋找設備選擇器','在 LIFX 應用或 https://cloud.lifx.com 中，找到您的裝置標籤或 ID。您可以使用“全部”來控制所有設備。','{"selector": "LIFX 設備選擇器。可以是設備名稱、ID、群組名稱或全部。例如：客廳燈"}'),
('lifx-zh-4', 'lifx', 'zh', 4,                                                                                       '輸入憑證','貼上您的 API 令牌。輸入您的裝置選擇器（例如，「客廳燈」或「全部」）。','{"api_key": "您的 LIFX 個人 API 令牌，來自 https://cloud.lifx.com/settings", "selector": "LIFX 裝置選擇器。可以是裝置名稱、ID、群組名稱或全部。例如：客廳燈"}'),
('lifx-zh-5', 'lifx', 'zh', 5,                                                                                       '測試連接',,'{}');
                                                                                                                     
-- Insert WiZ guides (English only for now)                                                                          
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES         '點擊「測試憑證」以驗證您的令牌和裝置是否可存取。'
('wiz-zh-1', 'wiz', 'zh', 1,                                                                                         '尋找控制器','在您的本機網路上找到您的 WiZ 裝置 IP 位址。檢查您的路由器或 WiZ 應用程式。', '{}'),
('wiz-zh-2', 'wiz', 'zh', 2,                                                                                         '取得授權令牌','使用 WiZ 應用程式產生用於本機存取的 API 令牌或驗證金鑰。','{"api_key": "WiZ 裝置本地 API 存取的授權令牌。"}'),
('wiz-zh-3', 'wiz', 'zh', 3,                                                                                         '輸入 IP 位址和令牌','輸入您的 WiZ 裝置 IP 位址和驗證令牌。','{"device_ip": "WiZ 裝置在本機網路上的 IP 位址。例如：192.168.1.100", "api_key": "WiZ 裝置本機 API 存取的授權令牌。"}'),
('wiz-zh-4', 'wiz', 'zh', 4,                                                                                         '測試連接','點擊「測試憑證」以驗證裝置是否回應正確。', '{}');
                                                                                                                                                                                                                                                                                    
-- Insert Nanoleaf guides (English only for now)                                                                                                                                                                                                                                    
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('nanoleaf-zh-1', 'nanoleaf', 'zh', 1,                                                                               '尋找控制器','找到您的 Nanoleaf 控制器 IP 位址。您可以透過 Nanoleaf 應用程式或路由器存取它。','{}'),
('nanoleaf-zh-2', 'nanoleaf', 'zh', 2,                                                                               '啟用 API','Nanoleaf 設備本地運行著一個 API。您只需要它的 IP 位址和授權令牌。','{}'),
('nanoleaf-zh-3', 'nanoleaf', 'zh', 3,                                                                               '產生令牌','按住電源按鈕 5 秒鐘，直到它開始閃爍。這將啟用 API。然後使用以下指令產生令牌：curl -X POST http://[IP]:[PORT]/api/v1/new','{"api_key": "Nanoleaf 裝置產生的授權令牌。"}'),
('nanoleaf-zh-4', 'nanoleaf', 'zh', 4,                                                                               '輸入詳細信息','輸入您的 Nanoleaf 裝置 IP 位址和您產生的授權令牌。','{"device_ip": "Nanoleaf 裝置在本機網路上的 IP 位址。例如：192.168.1.100", "api_key": "Nanoleaf 裝置產生的授權令牌。"}'),
('nanoleaf-zh-5', 'nanoleaf', 'zh', 5,                                                                               '測試連接','點擊「測試憑證」以驗證與裝置的本機連線。','{}');
                                                                                                                                                                                                                                                                                    
-- Insert TP-Link Kasa guides (English only for now)                                                                                                                                                                                                                                
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('tp-link-kasa-zh-1', 'kasa', 'zh', 1,                                                                               '尋找設備 IP','請使用 Kasa 應用或查看您的路由器查找設備的本機 IP 位址。','{}'),
('tp-link-kasa-zh-2', 'kasa', 'zh', 2,                                                                               '記錄設備 IP','Kasa 智慧型裝置運行本機 API。您只需要它在您網路中的 IP 位址。','{}'),
('tp-link-kasa-zh-3', 'kasa', 'zh', 3,                                                                               '驗證本機存取權限','請確保您的門戶伺服器可以存取該設備。位於 VPN 或防火牆後面的設備可能無法正常工作。','{}'),
('tp-link-kasa-zh-4', 'kasa', 'zh', 4,                                                                               '輸入 IP 位址','請按以下格式輸入您的設備 IP 位址：192.168.1.50','{"device_ip": "您本地網路上 Kasa 設備的 IP 位址。例如：192.168.1.100"}'),
('tp-link-kasa-zh-5', 'kasa', 'zh', 5,                                                                               '測試連接','點擊‘測試憑證’以驗證您的裝置是否可存取。','{}');
                                                                                                                                                                                                                                                                                    
-- Insert Yeelight guides (English only for now)                                                                                                                                                                                                                                    
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('yeelight-zh-1', 'yeelight', 'zh', 1,                                                                               '尋找設備 IP','在 Yeelight 應用程式中，前往「裝置設定」。您將看到設備的 IP 位址。','{}'),
('yeelight-zh-2', 'yeelight', 'zh', 2,                                                                               '啟用本地控制','在 Yeelight 應用程式中，請確保已在裝置設定中啟用「本機網路控制」。','{}'),
('yeelight-zh-3', 'yeelight', 'zh', 3,                                                                               '記下 IP 位址','從設定頁面複製設備 IP 位址。','{"device_ip": "您本地網路上 Yeelight 裝置的 IP 位址。例如：192.168.1.100"}'),
('yeelight-zh-4', 'yeelight', 'zh', 4,                                                                               '輸入 IP 位址','輸入您的 Yeelight 設備 IP 位址。','{"device_ip": "您本地網路上 Yeelight 裝置的 IP 位址。例如：192.168.1.100"}'),
('yeelight-zh-5', 'yeelight', 'zh', 5,                                                                               '測試連接','點擊「測試憑證」以驗證您的裝置是否可透過網路存取。','{}');
                                                                                                                                                                                                                                                                                    
-- Insert WLED guides (English only for now)                                                                                                                                                                                                                                        
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('wled-zh-1', 'wled', 'zh', 1,                                                                                       '尋找設備 IP','連接到您的 WLED 裝置。您可以在路由器或 WLED 的 Web 管理介面中找到裝置的 IP 位址。','{}'),
('wled-zh-2', 'wled', 'zh', 2,                                                                                       '本地控制','WLED 裝置運行本機 API。通常無需身份驗證，只需設備 IP 位址即可。','{}'),
('wled-zh-3', 'wled', 'zh', 3,                                                                                       '測試訪問','確保您的入口網站可以存取該裝置（同一網路或 VPN）。','{}'),
('wled-zh-4', 'wled', 'zh', 4,                                                                                       '輸入 IP 位址','輸入您的 WLED 設備 IP 位址。','{"device_ip": "您本地網路上 WLED 裝置的 IP 位址。例如：192.168.1.100"}'),
('wled-zh-5', 'wled', 'zh', 5,                                                                                       '測試連接','點擊“測試憑證”以驗證設備是否響應。','{}');
                                                                                                                                                                                                                                                                                    
-- Insert Wyze guides (English only for now)                                                                                                                                                                                                                                        
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('wyze-zh-1', 'wyze', 'zh', 1,                                                                                       '不支持','目前我們不支援透過直接 API 整合 Wyze。我們正在研究 OAuth 方案。' ,'{}'),
('wyze-zh-2', 'wyze', 'zh', 2,                                                                                       '更多資訊','請稍後查看 Wyze 支援方面的更新。' ,'{}');
                                                                                                                                                                                                                                                                                    
-- Insert Amazon Alexa guides (English only for now)                                                                                                                                                                                                                                
INSERT INTO brand_setup_guides (id, brand_id, language_code, step_order, title, content, help_fields) VALUES                                                                                                                                                                        
('amazon-alexa-zh-1', 'amazon', 'zh', 1,                                                                             '外部應用','亞馬遜 Alexa 整合採用外部流程。請透過官方 Alexa 應用控制您的 Alexa 裝置。'     ,'{}'),
('amazon-alexa-zh-2', 'amazon', 'zh', 2,                                                                             '即將推出','原生 Alexa 整合計劃在未來的版本中推出。'     ,'{}');
